# Generated by Django 5.2.8 on 2025-11-28 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gov_info',
            name='gov_dept',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gov_info',
            name='gov_desg',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gov_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ngo_info',
            name='ngo_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ngo_info',
            name='ngo_pic',
            field=models.ImageField(upload_to='media/ngo'),
        ),
        migrations.AlterField(
            model_name='ngo_info',
            name='reg_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ngo_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vol_info',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vol_info',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vol_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='img_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/images')),
                ('time', models.TimeField(auto_now_add=True)),
                ('location', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
