# Generated by Django 5.2.8 on 2025-11-28 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_gov_info_gov_dept_alter_gov_info_gov_desg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='verified_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/images')),
                ('time', models.TimeField(auto_now_add=True)),
                ('location', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.img_post')),
            ],
        ),
    ]
