# Generated by Django 5.2.8 on 2025-11-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verified_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='verified_post',
            name='status',
            field=models.CharField(default='Pending', max_length=40),
        ),
    ]
